export const BASEHUB_KNOWLEDGE = [
  {
    id: 'swap',
    title: 'SwapHub',
    category: 'dex',
    description: 'BaseHub token swap surface on Base.',
    currentlyExecutableByBurner: true,
  },
  {
    id: 'flip-game',
    title: 'Coin Flip',
    category: 'gaming',
    description: 'BaseHub onchain coin flip game.',
    currentlyExecutableByBurner: true,
  },
  {
    id: 'dice-roll',
    title: 'Dice Roll',
    category: 'gaming',
    description: 'BaseHub onchain dice game.',
    currentlyExecutableByBurner: true,
  },
  {
    id: 'slot',
    title: 'Crypto Slots',
    category: 'gaming',
    description: 'BaseHub slot-style game.',
    currentlyExecutableByBurner: false,
  },
  {
    id: 'lucky-number',
    title: 'Lucky Number',
    category: 'gaming',
    description: 'BaseHub number-guessing game.',
    currentlyExecutableByBurner: true,
  },
  {
    id: 'early-access',
    title: 'Early Access Pass',
    category: 'nft',
    description: 'BaseHub early access NFT mint.',
    currentlyExecutableByBurner: false,
  },
  {
    id: 'free-nft-mint',
    title: 'NFT Launchpad',
    category: 'nft',
    description: 'BaseHub NFT Launchpad free mint surface.',
    currentlyExecutableByBurner: true,
  },
  {
    id: 'prediction-arena',
    title: 'Prediction Arena',
    category: 'nft',
    description: 'BaseHub yes/no prediction surface.',
    currentlyExecutableByBurner: false,
  },
  {
    id: 'deploy',
    title: 'Deploy Token',
    category: 'deploy',
    description: 'BaseHub token deployment flow.',
    currentlyExecutableByBurner: false,
  },
  {
    id: 'deploy-erc721',
    title: 'Deploy ERC721',
    category: 'deploy',
    description: 'BaseHub ERC721 collection deployment flow.',
    currentlyExecutableByBurner: false,
  },
  {
    id: 'deploy-erc1155',
    title: 'Deploy ERC1155',
    category: 'deploy',
    description: 'BaseHub ERC1155 collection deployment flow.',
    currentlyExecutableByBurner: false,
  },
  {
    id: 'pumphub-buy',
    title: 'PumpHub Buy',
    category: 'trade',
    description: 'BaseHub token micro-buy surface on PumpHub.',
    currentlyExecutableByBurner: true,
  },
  {
    id: 'pumphub-sell',
    title: 'PumpHub Sell',
    category: 'trade',
    description: 'BaseHub token micro-sell surface on PumpHub.',
    currentlyExecutableByBurner: true,
  },
  {
    id: 'swaphub-swap',
    title: 'SwapHub Swap',
    category: 'trade',
    description: 'BaseHub DEX micro-swap surface on SwapHub.',
    currentlyExecutableByBurner: true,
  },
  {
    id: 'wallet-analysis',
    title: 'Wallet Analysis',
    category: 'analysis',
    description: 'BaseHub wallet inspection tool.',
    currentlyExecutableByBurner: false,
  },
  {
    id: 'base-guild',
    title: 'Base Guild Companion',
    category: 'guild',
    description: 'BaseHub guild mission companion.',
    currentlyExecutableByBurner: false,
  },
  {
    id: 'gm-game',
    title: 'GM Game',
    category: 'simple',
    description: 'Low-cost BaseHub GM contract interaction on Base.',
    currentlyExecutableByBurner: true,
  },
  {
    id: 'gn-game',
    title: 'GN Game',
    category: 'simple',
    description: 'Low-cost BaseHub GN contract interaction on Base.',
    currentlyExecutableByBurner: true,
  },
]

export function getBaseHubKnowledgeSummary() {
  return BASEHUB_KNOWLEDGE
}
